# ░█▀█░█░░░█▀█░█▀█░░░█▀▀░█░█░█▀█░█░█░█▀█
# ░█▀█░█░░░█▀█░█░█░░░█░░░█░█░█░█░█▀█░█▀█
# ░▀░▀░▀▀▀░▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀░▀░▀░▀░▀░▀
# ======================================
# Full documentation: https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

# Fallback wallpaper (applies to all monitors when monitor is empty)
wallpaper {
    monitor =
    path = $WALLPAPER
    fit_mode = cover
}
