return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'bash',
        'c',
        'diff',
        'html',
        'lua',
        'luadoc',
        'markdown',
        'markdown_inline',
        'typescript',
        'query',
        'vim',
        'vimdoc',
        'rust',
        'regex',
        'sql',
        'html',
        'css',
        'javascript',
        'yaml',
        'json',
        'toml',
        'gdscript',
        'godot_resource',
        'elixir',
        'eex',
        'heex',
      },
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = {
          'ruby',
          'markdown',
        },
      },
      indent = {
        enable = true,
        disable = { 'ruby' },
      },
    },
  },
}
