return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  dependencies = {
    'echasnovski/mini.nvim',
  },
  opts = {
    delay = 0,
    preset = 'modern',
    sort = {
      'local',
      'order',
      'group',
      'alphanum',
      'mod',
    },

    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    spec = {
      { '<leader>f', group = 'Find' },
      { '<leader>y', group = 'Yazi' },
      { '<leader>t', group = 'Toggle' },
      { '<leader>b', group = 'Buffers' },
      { '<leader>e', group = 'Explorer', icon = { icon = '' } },
      { '<leader>s', group = 'Spellcheck', icon = { icon = '󰓆' } },
      { '<leader>g', group = 'Miscellaneous', icon = { icon = '' } },
      { '<leader>z', group = 'Zettels', icon = { icon = '' } },
      { '<leader>h', group = 'Git' },
      { 'gr', group = 'Code/LSP' },
      -- { '<leader>r', group = 'Code/LSP' },
    },
  },
}
