# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# Kitty OS Specific Environment
env = KT_OS_CACHE,$HOME/.cache/kitty-os
env = KT_OS_CONFIG,$HOME/.config/kitty-os
env = KT_OS_WALLPAPERS,$HOME/Pictures/Wallpapers
env = KT_OS_DEFAULT_WALLPAPER,$HOME/Pictures/Wallpapers/0.png
env = KT_OS_DEFAULT_THEME,tokyo-night
