[mgr]
linemode     = "size"
sort_by      = "natural"
show_hidden  = true
mouse_events = []

[preview]
wrap       = "yes"
max_width  = 1500
max_height = 1500


[opener]
pdf = [
  { run = 'zathura "$1"', desc = "zathura", block = false },
]
image = [
  { run = 'nsxiv "$@"', desc = "nsxiv", block = false },
]
text = [
  { run = 'less "$1"', desc = "less", block = true },
]
edit = [
  { run = 'nvim "$1"', desc = "nvim", block = true },
]
video = [
    { run = 'mpv "$1"', desc = "mpv", block = false },
]
audio = [
  { run = 'mpv --force-window "$1"', desc = "mpv", block = false },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
  # Mime types
  { mime = "application/pdf", use = "pdf" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "text/*", use = ["edit", "text"] },

  # File extensions
  { name = "*.pdf", use = "pdf" },
  { name = "*.json", use = "edit" },
  { name = "*.md", use = "edit" },
  { name = "*.html", use = ["edit", "text"] },
  { name = "*.sh", use = "edit" },
  { name = "*.txt", use = ["edit", "text"] },
  { name = "*.csv", use = "edit" },
  { name = "*.dat", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
  { name = "*.lua", use = ["edit", "text"] },
  { name = "*.log", use = "text" },
  { name = "*.rs", use = ["edit", "text"] },
  { name = "*.js", use = ["edit", "text"] },
  { name = "*.ts", use = ["edit", "text"] },
  { name = "*.mp3", use = "audio" },
  { name = "*.wav", use = "audio" },
  { name = "*.ogg", use = "audio" },
]
